baseURL: "https://younghomseminar.github.io/"
title: YoungHom
paginate: 10
theme: PaperMod
copyright: " "
publishDir: docs

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false
enableEmoji: true


minify:
    disableXML: true
    # minifyOutput: true



    
outputs:
    home:
        - HTML
        - RSS
        - JSON

menu:
    main:   
      - name: Schedule
        url: schedule/
        weight: 5
      - name: Archive
        url: archives/
        weight: 10
      - name: Sign up
        url: "https://forms.gle/ULs3gJjLnu7LcYxr9"
        weight: 15
      - name: Recordings
        url: "https://www.youtube.com/@Young-HOM"
        weight: 20 
      - name: About
        url: about/
        weight: 25     





params:
    # env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Young Homotopy-theorist Online Meeting"
    author: 

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowToc: false
    cover:
        responsiveImages: false
        hiddenInSingle: true 
    # hidesummary: true
    # comments: true

    # images: ["papermod-cover.png"]

#    homeInfoParams:
#        Title: Young Homotopy-theorist Online Meeting 
#        Content: > 
#                  ![Error loading image](frontpage.png)
                 

    profileMode:
          enabled: true
          title: Young Homotopy-theorist Online Meeting
          imageUrl: "frontpage.png"
          imageTitle: Generated by DALL-E 2 using "homotopy theory, pattern painting"
          imageWidth: 450
          imageHeight: 400
          subtitle: ""

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
     goldmark:
        renderer:
            unsafe: true


    